#!/bin/bash
# n8n Production Playbook — One-Click Setup
echo "========================================="
echo "  n8n Production Playbook - Setup"
echo "  by ErgeneAI"
echo "========================================="
echo ""
echo "1. Read n8n-playbook.pdf for deployment guide"
echo "2. Check API_KEYS.md for required credentials"
echo "3. Import workflows from 'workflows/' folder"
echo ""
echo "Quick start with Docker:"
echo "  docker run -d --name n8n \\"
echo "    -p 5678:5678 \\"
echo "    -v n8n_data:/home/node/.n8n \\"
echo "    n8nio/n8n"
echo ""
echo "For production setup, see Chapter 1 of the PDF."
echo "========================================="
